/**
 * Bulk locality import for programmatic SEO scaling.
 *
 * Usage:
 *   npx tsx scripts/import-localities.ts data/localities/bangalore-batch.json
 *
 * Input JSON shape:
 * [
 *   { "slug": "whitefield", "name": "Whitefield", "locationId": "loc-bangalore", "nearbyAreaIds": ["area-marathahalli"] }
 * ]
 *
 * Output: TypeScript batch file ready to import in initial-areas.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

type LocalityInput = {
  slug: string;
  name: string;
  locationId: "loc-bangalore" | "loc-mysore" | "loc-visakhapatnam";
  nearbyAreaIds: string[];
  propertyTypes?: string[];
  traits?: string;
};

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: npx tsx scripts/import-localities.ts <input.json> [output.ts]");
  process.exit(1);
}

const outputPath =
  process.argv[3] ?? resolve(dirname(inputPath), `generated-${Date.now()}.ts`);

const raw = readFileSync(resolve(inputPath), "utf8");
const rows = JSON.parse(raw) as LocalityInput[];

if (!Array.isArray(rows) || rows.length === 0) {
  console.error("Input must be a non-empty JSON array.");
  process.exit(1);
}

const compactLines = rows.map((row) => {
  const parts = [
    `slug: "${row.slug}"`,
    `name: "${row.name.replace(/"/g, '\\"')}"`,
    `locationId: "${row.locationId}"`,
    `nearbyAreaIds: [${row.nearbyAreaIds.map((id) => `"${id}"`).join(", ")}]`,
  ];
  if (row.traits) {
    parts.push(`traits: "${row.traits.replace(/"/g, '\\"')}"`);
  }
  return `  { ${parts.join(", ")} },`;
});

const fileContent = `import { buildAreasFromCompact } from "./area-factory";

/** Auto-generated by scripts/import-localities.ts — ${rows.length} localities → ${rows.length * 10} URLs */
export const SCALABLE_AREAS_BATCH_GENERATED = buildAreasFromCompact([
${compactLines.join("\n")}
]);
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContent, "utf8");

console.log("Import Localities Summary");
console.log("=========================");
console.log(`Input rows: ${rows.length}`);
console.log(`Estimated pages: ${rows.length * 10} (1 area + 9 service-area per locality)`);
console.log(`Output: ${outputPath}`);
console.log("");
console.log("Next: import SCALABLE_AREAS_BATCH_GENERATED in src/data/initial-areas.ts");
